kind: pipeline
name: doh-client

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ich777/doh-client
    username: ich777
    password:
      from_secret: docker_password
    tags: latest